services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      BACKEND_URL: http://api:8000
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app/package-lock.json
          action: rebuild
        - path: ./app/next.config.mjs
          action: rebuild
        - path: ./app
          target: /app
          action: sync

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api/db.sqlite3:/app/db.sqlite3
    environment:
      DATABASE_URL: sqlite://db.sqlite3
    develop:
      watch:
        - path: ./api/requirements.txt
          action: rebuild
        - path: ./api/manage.py
          action: rebuild
        - path: ./api/CRUD
          action: rebuild
        - path: ./api
          target: /api
          action: sync
